# Generated by Django 2.2.5 on 2019-09-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='crse',
            new_name='Course_Name',
        ),
    ]
