# Generated by Django 2.2.5 on 2019-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Batch_Code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
