# Generated by Django 2.2.5 on 2019-10-22 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import timetable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_Code', models.CharField(max_length=256, unique=True)),
                ('Starting_Date', models.DateField()),
                ('Fees', models.IntegerField()),
                ('Active_Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(max_length=256, unique=True)),
                ('No_of_Students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.TimeField(default=datetime.datetime.now)),
                ('End_Time', models.TimeField()),
                ('Date', models.DateField(default=timetable.models.next_day)),
                ('Class_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.ClassRoom')),
                ('Select_Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Course'),
        ),
    ]
