# Generated by Django 2.2.5 on 2019-09-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=150)),
                ('desig', models.CharField(max_length=150)),
                ('sal', models.IntegerField(default=15000)),
            ],
        ),
    ]
